name: Push Events
on: 
  push:
    branches:
    - test
  # issues:
  #   types:
  #   - opened
  # schedule:
  # - cron: '*/5 * * * *' #run every five minutes
jobs:
  show-info:
    runs-on: ubuntu-latest
    steps:
    - name: info
      run: |
        echo "This is a scheduled event at $(date)"
